fix: Installation of “gnome-bluetooth” has been replaced by aur package - “gnome-bluetooth-3.0”, due to a bug:
ImportError: gnome-bluetooth-3 is not installed, please install it first